version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ktor-net

  ktor:
    image: modeart-1.4.0:latest
    container_name: ktor-server
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - ktor-net
    volumes:
      - ./static:/app/static

networks:
  ktor-net:
    driver: bridge